go.property("facing", 0)
go.property("pos_x", 0)
go.property("pos_y", 0)

function init(self)
	model.play_anim("#model", "female_mage_v002_die", go.PLAYBACK_LOOP_PINGPONG)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("select") then
		go.set("#model", "tint", vmath.vector4(0, 1, 0, 1))
	elseif message_id == hash("unselect") then
		go.set("#model", "tint", vmath.vector4(1))
	end
end